project_name: RDRhelper
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  gitlab:
  prerelease: auto
env_files:
  # use only one or release will fail!
  github_token: ~/.path/to/my/gh_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.path/to/my/gitea_token
gitlab_urls:
  api: https://gitlab.consulting.redhat.com/api/v4
  download: https://gitlab.consulting.redhat.com
  # set to true if you use a self-signed certificate
  skip_tls_verify: false
